version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: your_db_user
      DB_PASS: your_db_password
      DB_NAME: your_db_name
      DB_PORT: 5432  # Default PostgreSQL port

  db:
    image: postgres
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
